### ISSUE TITLE
Czar confirm boxes not going away

### ISSUE THREAD

**Issue by stevenvergenz** [falkrons/HaH#10]
After the winning white card is selected the X and ✓ is still showing for czar( BUT kept clicking on ✓ during the next round and it worked and the ✓ went away) - ((or keep clicking on different areas of the ✓ or xtra long click)) (((FAST CLICKING A FEW TIMES GETS IT TO WORK)))

**Comment by schmidtec** [comment]
When czar is selecting between the players' answer cards, to pick the winning white card:

If czar just clicks player#1's white card, then clicks **✓** right away (without clicking back and forth between player#1 and player#2's white cards) the **X** and **✓** go away after the click!

((My issue was that it's fun to click between the 2 different players' cards and watch them animate up and down :) but if you just pick the white card and click **✓** right away this bug doesn't occur))

I think to fix this you must only be able to click the **X** to put that top white card back, and not have the ability for that lower 2nd white card to change places with the top card.

**Comment by schmidtec** [comment]
See: Party ball appears over non-winner? https://github.com/falkrons/HaH/issues/13

**Comment by stevenvergenz** [comment]
Okay, I think this is fixed. Turns out that it would spawn a new copy of the confirmation boxes every time `handleCzarSelection` was called, which exactly overlapped with the old ones. So you would click one set and they would disappear, but there's another set behind them. That's why multiple clicks seemed to fix it.

Tweaked it to remove the old ones first if present.
