### ISSUE TITLE
Party ball appears over non-winner?

### ISSUE THREAD

**Issue by stevenvergenz** [falkrons/HaH#13]
At the last meetup, some players noticed the celebratory confetti appearing over a player other than the one whose card(s) were chosen. Need to verify at next meeting.

**Comment by schmidtec** [comment]
Repro'd this.

Maybe this has something to do with the leftover X and ✓ issue.

Maybe the winner is the **first** card that gets picked and not necessarily the white card that gets the ✓.

**Comment by schmidtec** [comment]
If you pick the player#1 card, hit X, then pick the player#2 card, hit ✓, the confetti works correctly and appears over player#2. :: GOOD

If you pick the player#1 card, don't hit X, then pick the player#2 card, hit ✓, the confetti works incorrectly and appears over player#1. :: BAD

**Comment by stevenvergenz** [comment]
Re: my comment in #10, the different copies of the confirmation boxes had references to their corresponding players. So whichever one first received the click event is the one that reports a winner.
