### ISSUE TITLE
Sound effects?

### ISSUE THREAD

**Issue by stevenvergenz** [falkrons/HaH#14]
It would make the game a little more interesting to have some simple sounds emitted from the game. 

Suggestions:
- Drum roll, brass fanfare, pop effect timed to party ball
- Paper shuffling sound on deal
- Dialog box chime

**Comment by schmidtec** [comment]
Card flick sound. Maybe play this after they click ✓ to submit their white card:
https://github.com/falkrons/HaH/blob/master/client/audio/card_flick.wav

**Comment by stevenvergenz** [comment]
Merged with a32f5f8.
