### ISSUE TITLE
GearVR - font seems larger?

### ISSUE THREAD

**Issue by schmidtec** [falkrons/HaH#18]
Quite a few cards have text running off the side, even the main Holograms Against Humanity card.

**Comment by stevenvergenz** [comment]
Doesn't happen in any Android browser except for Altspace. Gonna be tricky to debug this :(

**Comment by falkrons** [comment]
could it have something to do with how altspace sizes the materials? I know the console always complains the materials arnt powers of 2, maybe the translation messes it up?

**Comment by falkrons** [comment]
![com altvr altspacevr_client-20160518-210414](https://cloud.githubusercontent.com/assets/12438319/15379945/ba41b1f4-1d3f-11e6-9ee8-8df156456a04.jpg)

**Comment by stevenvergenz** [comment]
Hopefully fixed in 018fa49. Need testing.

**Comment by falkrons** [comment]
So the font update did change things. Ill get the screenshot here in a bit. It did move the extra letter, but it put it on the other side of the card. so one side says "Hologram against Humanity" and the other side says "sHolograms against Humanity" All the letters were within the limits of each side of the card.

**Comment by schmidtec** [comment]
I was wondering if we are able to find the browser userAgent to determine if the player is using Gear (The Gear browser is a newer version and the Chromium browser on PC is really old right?) So if the browser is the newer version make the font size smaller.

**Comment by stevenvergenz** [comment]
As much as this solution bugs me, it's probably all we have. I'll get cracking, see if it's effective.

**Comment by stevenvergenz** [comment]
I added a 15% font size reduction for the mobile altspace browser, and it now works for at least one Gear VR client (Galaxy S7 / Marshmallow 6.0.1). Waiting for more confirmations that this is fixed before closing the issue.

**Comment by stevenvergenz** [comment]
Confirmed workaround, though if Altspace fixes the bug the workaround will break it again.
