### ISSUE TITLE
Implement suggestion form

### ISSUE THREAD

**Issue by stevenvergenz** [falkrons/HaH#27]
The game needs some way for players to report bugs, suggest enhancements, and author new cards. Possible Github integration?

**Comment by stevenvergenz** [comment]
For form authorization: https://developer.github.com/v3/oauth/

For issue filing: https://developer.github.com/v3/issues/#create-an-issue

Here's the flow I imagine:
1. User clicks the trigger in the game client, which presents the submission form.
2. They type in the issue type, title, body, and optionally an email address, and hit submit.
3. That information, along with their Altspace username, is sent to the server.
4. The server authenticates with Github using an account pre-configured for the form's use.
5. The server publishes a new issue to Github with the submitted information.

**Comment by GrumpyCrouton** [comment]
I think new cards should be authored using a simple html/php form that sends the development team (You) an email to a special email dedicated to just card submissions. With php you can even make it automatically format it properly in the email (Maybe adding new lines after so many characters or something).

**Comment by stevenvergenz** [comment]
Finally added in a useful manner as of ec96d53
