### ISSUE TITLE
Cards get stuck when becoming czar

### ISSUE THREAD

**Issue by stevenvergenz** [falkrons/HaH#38]
Seemingly randomly, cards will be dealt on top of other cards (or dealt to the czar), and will be locked there until the client reloads. No client or server errors when it happens. This is gonna be a pain in the ass to debug, I can tell :(

**Comment by piapple1** [comment]
![jay2016-06-05_22-35-38](https://cloud.githubusercontent.com/assets/19351300/15811032/61610076-2b72-11e6-80ef-0782bbbfbc5d.png)
![jay2016-06-05_22-35-52](https://cloud.githubusercontent.com/assets/19351300/15811034/66d3e532-2b72-11e6-91e8-3329b58cc454.png)
![jay2016-06-05_22-36-15](https://cloud.githubusercontent.com/assets/19351300/15811035/6a48511c-2b72-11e6-9d53-6a7511fa48a6.png)

Here are those screens from the game earlier.

**Comment by stevenvergenz** [comment]
I suspect that somehow, two cards end up in a single "spot" in the hand. So since the code assumes a single card, the other one gets left. The actual stuck card seems to rotate, so it's whatever card is second.

**Comment by stevenvergenz** [comment]
Fixed!
