### ISSUE TITLE
Table shifting

### ISSUE THREAD

**Issue by GrumpyCrouton** [falkrons/HaH#42]
I've noticed people complain quite a bit when people join/leave the game, because some people have a hard time moving around the table.

A solution I thought of may be to keep the max number of name cards on the table at all times, but leave them blank when a player is not associated with it, that way the table won't rotate when a new player joins/leaves, the nametag will just change.

This will also stop the question of how many people can be in a game at once, as that is a question I have heard a lot as well.

**Comment by stevenvergenz** [comment]
I've thought about this, it's not a bad idea! It will take a considerable amount of refactoring though, so don't expect this to happen overnight. I don't have as much time as I once did to work on this.
