### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by GrumpyCrouton** [falkrons/HaH#43]
I'm working on a system (http://valianware.com/suggest/) in which I (and possibly others if you guys want) can input my card ideas to get a list of them as I go instead of making a lot of updates to a pull request.

I'm stuck on the process, however, while I'm trying to make PHP automatically move my text down and insert line breaks by lines (this needs a lot of work) 

~~(Current progress can be seen here http://valianware.com/suggest/test.php?text=INPUT&creator=CreatorName&color=black just change the getter "text" to any text you desire.)~~

If you go to the page mentioned earlier (http://valianware.com/suggest/) you can input a suggestion and it will take you to a test page that shows how that card should render. I've got it down to almost always rendering the same breaks as I have put in manually in my card suggestions nearly every time, and should be generating the proper JSON format below the card rendering.

 (For cards with blanks, use a single underscore for blanks) currently, I have the font size at 30px.

The trouble I am having is I'm having a hard time finding out what the default font-size is suppose to be as it is dynamic in the source code (understandably).

So my question is, what is the default font-size before the code changes it at all?

**Comment by stevenvergenz** [comment]
There is no default font size per se, it's pegged to the resolution of the texture. It's set to 9% of the pixel width of the card texture, but we have to artificially reduce it on Gear VR for some reason. So that comes to a bold 23px sans-serif font on a 256px-wide card. Hope that helps.

We're working on a similar suggestion system that integrates with the game, so you can submit right from the table. It's still not instant inclusion as we want to check each card first, but it'll get the community involved again (hopefully).

**Comment by stevenvergenz** [comment]
Also, remember that not all black cards have blanks. Many are just questions.

**Comment by GrumpyCrouton** [comment]
Well every altspace player has an in-game browser, you can have some button on the table just launch the website on there and that may work? I'm not really sure. This is really just for me currently.

Good point on the blanks, I'll fix that.

I also changed the card renders to show 23px bold helvetica font.

**Comment by stevenvergenz** [comment]
I asked around about this, there's no way currently for enclosures to open a page on a user's personal browser. So it's gotta be a short URL that they can type.

**Comment by GrumpyCrouton** [comment]
What if you include some sort of user browser in the game itself? For example, user clicks a button and a dialogue comes up asking for their suggestion, they type that in and hit submit and then the server does the rest of the checking and returns if it went through or not?

This could later be expanded to include some type of blank white cards.

**Comment by stevenvergenz** [comment]
That was the original idea, but we'll have to see which provides a better experience. Having the form in-game means it's anchored to the enclosure and not the user.

**Comment by GrumpyCrouton** [comment]
True, but I don't think that is necessarily a bad thing. It kind of adds to the wonder that is VR in a way.

**Comment by stevenvergenz** [comment]
You'll be interested to know that the card suggestion form should go live this weekend! I'm gonna close this issue though, since it seems to be resolved.
