### ISSUE TITLE
Where do we hosted an edited version to be able to use in altspace

### ISSUE THREAD

**Issue by ghost** [falkrons/HaH#49]
So Last night i downloaded the source code and modified the deck to add a lot of cards (was adding for an hour) but i cant find how we are meant to host it to access in our events?  
the install instructions suggest we may need  access beyond your standard web host?
Original topic stems from https://www.reddit.com/r/AltspaceVR/comments/4uw8dl/confused_about_custom_eventsspaces/ 
I really want to test what i have added before adding more and want to make these available for others to play (the cards in the tables at the minute repeat way too much), and ofcourse any of the entrys i make im more then happy for anyone to use, including the original dev.  
so where do i go to host them? (for free ideally or really cheap if not)

**Comment by stevenvergenz** [comment]
Any webhost that supports Node.js will do. I think Heroku offers it. Though as I mentioned in the other issue, we'd much rather you let us integrate it into the main game.

**Comment by ghost** [comment]
yep got it sorted out in the end, as i said on the other issue, and yes if you want them you are more then welcome to use them (with no strings attached as to creator, number of cards used etc, link and more detailed response in the other issue page)
