### ISSUE TITLE
Cant interact with my AltSpace interface

### ISSUE THREAD

**Issue by CheeseJuggernaut** [falkrons/HaH#7]
I am unable to interact with the AltSpace UI because it is hidden under the table when playing. This could be fixed by lowering the table or something like that.

**Comment by stevenvergenz** [comment]
We've experimented with this a bit, but haven't come up with any good solutions to the menu accessibility problem yet. I'll leave this issue open for good measure, but it's unlikely this will be fixed any time soon.
